### ISSUE TITLE
BUG：开始插件后blender自动保存功能失效

### ISSUE THREAD

**Issue by xieqsei** [iloveyehan/uv_draw#1]
我使用的是blender 4.0.2，在开启uv_draw_1.4后，blender的”自动保存“失去作用。自动保存未能自动保存文件到目录，关闭插件后自动保存功能恢复。

**Comment by iloveyehan** [comment]
应该是线程的问题,下周修一下

**Comment by iloveyehan** [comment]
原因是blender在模态操作符下不会自动保存,现在只有在uv模式下不会自动保存了(要不停更新3d视图的顶点),其他模式能正常自动保存了

**Comment by iloveyehan** [comment]
1
